### ISSUE TITLE
ExcludedPermission causes PHP fatal

### ISSUE THREAD

**Issue by Reception123** [kulttuuri/SlackNotifications#35]
When we tried installing another extension after having installed SlackNotifications on MediaWiki 1.34 we got the following error. The usage of ExcludedPermission seems to be interfering with other extensions

```
PHP Fatal error:  Uncaught Exception: Unable to open file /srv/mediawiki/w/extensions/RegexFunctions/extension.json: filemtime(): stat failed for /srv/mediawiki/w/extensions/RegexFunctions/extension.json in /srv/mediawiki/w/includes/registration/ExtensionRegistry.php:136
Stack trace:
#0 /srv/mediawiki/w/includes/GlobalFunctions.php(52): ExtensionRegistry->queue('/srv/mediawiki/...')
#1 /srv/mediawiki/config/LocalExtensions.php(1131): wfLoadExtension('RegexFunctions')
#2 /srv/mediawiki/config/LocalSettings.php(3319): require_once('/srv/mediawiki/...')
#3 /srv/mediawiki/w/includes/Setup.php(124): require_once('/srv/mediawiki/...')
#4 /srv/mediawiki/w/maintenance/doMaintenance.php(83): require_once('/srv/mediawiki/...')
#5 /srv/mediawiki/w/extensions/ManageWiki/maintenance/toggleExtension.php(62): require_once('/srv/mediawiki/...')
#6 {main}
  thrown in /srv/mediawiki/w/includes/registration/ExtensionRegistry.php on line 136

Fatal error: Uncaught Exception: Unable to open file /srv/mediawiki/w/extensions/RegexFunctions/extension.json: filemtime(): stat failed for /srv/mediawiki/w/extensions/RegexFunctions/extension.json in /srv/mediawiki/w/includes/registration/ExtensionRegistry.php:136
Stack trace:
#0 /srv/mediawiki/w/includes/GlobalFunctions.php(52): ExtensionRegistry->queue('/srv/mediawiki/...')
#1 /srv/mediawiki/config/LocalExtensions.php(1131): wfLoadExtension('RegexFunctions')
#2 /srv/mediawiki/config/LocalSettings.php(3319): require_once('/srv/mediawiki/...')
#3 /srv/mediawiki/w/includes/Setup.php(124): require_once('/srv/mediawiki/...')
#4 /srv/mediawiki/w/maintenance/doMaintenance.php(83): require_once('/srv/mediawiki/...')
#5 /srv/mediawiki/w/extensions/ManageWiki/maintenance/toggleExtension.php(62): require_once('/srv/mediawiki/...')
#6 {main}
  thrown in /srv/mediawiki/w/includes/registration/ExtensionRegistry.php on line 136
zppix@mw4:/srv/mediawiki/w/extensions/ManageWiki/maintenance$ sudo -u www-data php toggleExtension.php --disable  regexfunctions --wiki testwiki
PHP Fatal error:  Uncaught Exception: Unable to open file /srv/mediawiki/w/extensions/RegexFunctions/extension.json: filemtime(): stat failed for /srv/mediawiki/w/extensions/RegexFunctions/extension.json in /srv/mediawiki/w/includes/registration/ExtensionRegistry.php:136
Stack trace:
#0 /srv/mediawiki/w/includes/GlobalFunctions.php(52): ExtensionRegistry->queue('/srv/mediawiki/...')
#1 /srv/mediawiki/config/LocalExtensions.php(1131): wfLoadExtension('RegexFunctions')
#2 /srv/mediawiki/config/LocalSettings.php(3319): require_once('/srv/mediawiki/...')
#3 /srv/mediawiki/w/includes/Setup.php(124): require_once('/srv/mediawiki/...')
#4 /srv/mediawiki/w/maintenance/doMaintenance.php(83): require_once('/srv/mediawiki/...')
#5 /srv/mediawiki/w/extensions/ManageWiki/maintenance/toggleExtension.php(62): require_once('/srv/mediawiki/...')
#6 {main}
  thrown in /srv/mediawiki/w/includes/registration/ExtensionRegistry.php on line 136

Fatal error: Uncaught Exception: Unable to open file /srv/mediawiki/w/extensions/RegexFunctions/extension.json: filemtime(): stat failed for /srv/mediawiki/w/extensions/RegexFunctions/extension.json in /srv/mediawiki/w/includes/registration/ExtensionRegistry.php:136
Stack trace:
#0 /srv/mediawiki/w/includes/GlobalFunctions.php(52): ExtensionRegistry->queue('/srv/mediawiki/...')
#1 /srv/mediawiki/config/LocalExtensions.php(1131): wfLoadExtension('RegexFunctions')
#2 /srv/mediawiki/config/LocalSettings.php(3319): require_once('/srv/mediawiki/...')
#3 /srv/mediawiki/w/includes/Setup.php(124): require_once('/srv/mediawiki/...')
#4 /srv/mediawiki/w/maintenance/doMaintenance.php(83): require_once('/srv/mediawiki/...')
#5 /srv/mediawiki/w/extensions/ManageWiki/maintenance/toggleExtension.php(62): require_once('/srv/mediawiki/...')
#6 {main}
  thrown in /srv/mediawiki/w/includes/registration/ExtensionRegistry.php on line 136

```

**Comment by kulttuuri** [comment]
Yeah, that option should actually be $wgSlackExcludedPermission (add Slack before the option so that we do not interfere with anything). I will change name of this variable now.

**Comment by kulttuuri** [comment]
Done! Let me know if there are still issues and I will tackle them. Closing this issue now :)

**Comment by Reception123** [comment]
Thanks! I'll test it out
